module.exports = Object.freeze({
  OPFactions: "opfactions",
  OPPrison: "opprison",
  OPSkyblock: "opskyblock",
  ClassicSkyblock: "classicskyblock",
  Survival: "survival",
  KitPvP: "kitpvp",
  UnrankedPractice: "unrankedpractice",
  RankedPractice: "rankedpractice",
  BedWars: "bedwars",
  SkyWars: "skywars",
  LifeSteal: "lifesteal",
  OPLifesteal: "oplifesteal",
  SkyPvP: "skypvp",
});
